<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TrocaTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('trocas')->insert([
            'unidade_id' => 2,
            'user1_id' => 7,
            'turma1_id' => 1,
            'user2_id' => 8,
            'turma2_id' => 1,
            'data1' => '2018-6-3',
            'turno1_id' => 1,
            'tipo1_id' => 1,
            'tipo2_id' => 2,
            'data1' => '2018-6-4',
            'turno2_id' => 2,
            'tipo3_id' => 2,
            'tipo4_id' => 1,
            'situacao_id' => 2,
        ]);
        DB::table('trocas')->insert([
            'unidade_id' => 2,
            'user1_id' => 9,
            'turma1_id' => 4,
            'user2_id' => 10,
            'turma2_id' => 3,
            'data1' => '2018-6-2',
            'turno1_id' => 1,
            'tipo1_id' => 2,
            'tipo2_id' => 1,
            'data1' => '2018-6-1',
            'turno2_id' => 2,
            'tipo3_id' => 1,
            'tipo4_id' => 2,
            'situacao_id' => 2,
        ]);
        DB::table('trocas')->insert([
            'unidade_id' => 2,
            'user1_id' => 7,
            'turma1_id' => 1,
            'user2_id' => 10,
            'turma2_id' => 1,
            'data1' => '2018-6-3',
            'turno1_id' => 1,
            'tipo1_id' => 1,
            'tipo2_id' => 2,
            'data1' => '2018-6-4',
            'turno2_id' => 2,
            'tipo3_id' => 2,
            'tipo4_id' => 1,
            'situacao_id' => 2,
        ]);
        DB::table('trocas')->insert([
            'unidade_id' => 2,
            'user1_id' => 9,
            'turma1_id' => 4,
            'user2_id' => 8,
            'turma2_id' => 3,
            'data1' => '2018-6-2',
            'turno1_id' => 1,
            'tipo1_id' => 2,
            'tipo2_id' => 1,
            'data1' => '2018-6-1',
            'turno2_id' => 2,
            'tipo3_id' => 1,
            'tipo4_id' => 2,
            'situacao_id' => 2,
        ]);
        DB::table('trocas')->insert([
            'unidade_id' => 3,
            'user1_id' => 11,
            'turma1_id' => 1,
            'user2_id' => 12,
            'turma2_id' => 1,
            'data1' => '2018-6-3',
            'turno1_id' => 1,
            'tipo1_id' => 1,
            'tipo2_id' => 2,
            'data1' => '2018-6-4',
            'turno2_id' => 2,
            'tipo3_id' => 2,
            'tipo4_id' => 1,
            'situacao_id' => 2,
        ]);
        DB::table('trocas')->insert([
            'unidade_id' => 3,
            'user1_id' => 13,
            'turma1_id' => 4,
            'user2_id' => 14,
            'turma2_id' => 3,
            'data1' => '2018-6-2',
            'turno1_id' => 1,
            'tipo1_id' => 2,
            'tipo2_id' => 1,
            'data1' => '2018-6-1',
            'turno2_id' => 2,
            'tipo3_id' => 1,
            'tipo4_id' => 2,
            'situacao_id' => 2,
        ]);
        DB::table('trocas')->insert([
            'unidade_id' => 3,
            'user1_id' => 11,
            'turma1_id' => 1,
            'user2_id' => 14,
            'turma2_id' => 1,
            'data1' => '2018-6-3',
            'turno1_id' => 1,
            'tipo1_id' => 1,
            'tipo2_id' => 2,
            'data1' => '2018-6-4',
            'turno2_id' => 2,
            'tipo3_id' => 2,
            'tipo4_id' => 1,
            'situacao_id' => 2,
        ]);
        DB::table('trocas')->insert([
            'unidade_id' => 3,
            'user1_id' => 13,
            'turma1_id' => 4,
            'user2_id' => 12,
            'turma2_id' => 3,
            'data1' => '2018-6-2',
            'turno1_id' => 1,
            'tipo1_id' => 2,
            'tipo2_id' => 1,
            'data1' => '2018-6-1',
            'turno2_id' => 2,
            'tipo3_id' => 1,
            'tipo4_id' => 2,
            'situacao_id' => 2,
        ]);
        DB::table('trocas')->insert([
            'unidade_id' => 4,
            'user1_id' => 15,
            'turma1_id' => 1,
            'user2_id' => 16,
            'turma2_id' => 1,
            'data1' => '2018-6-3',
            'turno1_id' => 1,
            'tipo1_id' => 1,
            'tipo2_id' => 2,
            'data1' => '2018-6-4',
            'turno2_id' => 2,
            'tipo3_id' => 2,
            'tipo4_id' => 1,
            'situacao_id' => 2,
        ]);
        DB::table('trocas')->insert([
            'unidade_id' => 4,
            'user1_id' => 17,
            'turma1_id' => 4,
            'user2_id' => 18,
            'turma2_id' => 3,
            'data1' => '2018-6-2',
            'turno1_id' => 1,
            'tipo1_id' => 2,
            'tipo2_id' => 1,
            'data1' => '2018-6-1',
            'turno2_id' => 2,
            'tipo3_id' => 1,
            'tipo4_id' => 2,
            'situacao_id' => 2,
        ]);
        DB::table('trocas')->insert([
            'unidade_id' => 4,
            'user1_id' => 15,
            'turma1_id' => 1,
            'user2_id' => 18,
            'turma2_id' => 1,
            'data1' => '2018-6-3',
            'turno1_id' => 1,
            'tipo1_id' => 1,
            'tipo2_id' => 2,
            'data1' => '2018-6-4',
            'turno2_id' => 2,
            'tipo3_id' => 2,
            'tipo4_id' => 1,
            'situacao_id' => 2,
        ]);
        DB::table('trocas')->insert([
            'unidade_id' => 4,
            'user1_id' => 17,
            'turma1_id' => 4,
            'user2_id' => 16,
            'turma2_id' => 3,
            'data1' => '2018-6-2',
            'turno1_id' => 1,
            'tipo1_id' => 2,
            'tipo2_id' => 1,
            'data1' => '2018-6-1',
            'turno2_id' => 2,
            'tipo3_id' => 1,
            'tipo4_id' => 2,
            'situacao_id' => 2,
        ]);
        DB::table('trocas')->insert([
            'unidade_id' => 5,
            'user1_id' => 19,
            'turma1_id' => 1,
            'user2_id' => 20,
            'turma2_id' => 1,
            'data1' => '2018-6-3',
            'turno1_id' => 1,
            'tipo1_id' => 1,
            'tipo2_id' => 2,
            'data1' => '2018-6-4',
            'turno2_id' => 2,
            'tipo3_id' => 2,
            'tipo4_id' => 1,
            'situacao_id' => 2,
        ]);
        DB::table('trocas')->insert([
            'unidade_id' => 5,
            'user1_id' => 21,
            'turma1_id' => 4,
            'user2_id' => 22,
            'turma2_id' => 3,
            'data1' => '2018-6-2',
            'turno1_id' => 1,
            'tipo1_id' => 2,
            'tipo2_id' => 1,
            'data1' => '2018-6-1',
            'turno2_id' => 2,
            'tipo3_id' => 1,
            'tipo4_id' => 2,
            'situacao_id' => 2,
        ]);
        DB::table('trocas')->insert([
            'unidade_id' => 5,
            'user1_id' => 19,
            'turma1_id' => 1,
            'user2_id' => 22,
            'turma2_id' => 1,
            'data1' => '2018-6-3',
            'turno1_id' => 1,
            'tipo1_id' => 1,
            'tipo2_id' => 2,
            'data1' => '2018-6-4',
            'turno2_id' => 2,
            'tipo3_id' => 2,
            'tipo4_id' => 1,
            'situacao_id' => 2,
        ]);
        DB::table('trocas')->insert([
            'unidade_id' => 5,
            'user1_id' => 21,
            'turma1_id' => 4,
            'user2_id' => 20,
            'turma2_id' => 3,
            'data1' => '2018-6-2',
            'turno1_id' => 1,
            'tipo1_id' => 2,
            'tipo2_id' => 1,
            'data1' => '2018-6-1',
            'turno2_id' => 2,
            'tipo3_id' => 1,
            'tipo4_id' => 2,
            'situacao_id' => 2,
        ]);
    }
}
